[pytest]
pythonpath=.
markers =
    pace: tests for pace utils
    misc: tests for ordinary utils
    duration_parsing: tests for parsing utilities
    bucketing: tests for interval creation
    time_utils: tests for date functions
    data: tests for data loading, validation
    pandas_helpers: tests for dataframe utilities
    streamlit: tests for streamlit pages